- hosts: localhost
  gather_facts: no

  vars:
    username: "{{ uname }}"
    # ansible-itc
    password: "$6$rounds=656000$OLg7NBkmbfAiDoss$/6POpB8cxH17ZG3X8YuN8156orj4xgKaVxqgFWJANH2r9sjz7pL.RFcIlQhNN635QpiFpQgu6ryGK5dHeEXYT."
    ldir: lesson1_files

  tasks:
    - block:
        - name: Run Reverse Proxy on my container
          docker:
            name: "rproxy"
            image: tksarah/rproxy
            detach: true
            state: started
            ports:
              - "80:80"
            tty: true

      tags: rproxy

    - block:
        - name: Add user
          user: name={{ uname }} password={{ password }} shell=/bin/bash groups=docker append=yes

        - name: Copy files
          copy: src=./{{ ldir }} dest=/home/{{ uname }} owner={{ uname }} group={{ uname }} mode=0644

        - name: Change modef for a ***.sh
          file: path={{ item }} mode=0755
          with_items:
            - /home/{{ uname }}/{{ ldir }}/tools/setup.sh
            - /home/{{ uname }}/{{ ldir }}/tools/initial.sh
            - /home/{{ uname }}/{{ ldir }}/login.sh

        - name: Add a line in .bashrc
          lineinfile: dest=/home/{{ uname }}/.bashrc line="alias docker=\'echo \"You cannot docker command.\"\'"

      tags: users
      become_user: root
      become: true

    - block:
        - name: Run containers
          shell: "bash /home/{{ uname }}/{{ ldir }}/tools/initial.sh"
          register: output

        - debug: msg="{{ output.stdout }}"

        - name: Delete initial.sh
          file: path=/home/{{ uname }}/{{ ldir }}/tools/initial.sh state=absent

      tags: handson
      become_user: "{{ uname }}"
      become: true
